#spring.cloud.config.server.git.uri=C:\\ws\\edu\\micro\\config
server:
  port: 9000
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/haroonsin/starter-micro-services-config.git
          clone-on-start: true